### ISSUE TITLE
Not working with Uno >=3.10

### ISSUE THREAD

**Issue by TopperDEL** [XamlFlair/XamlFlair#92]
I have a project that uses XamlFlair.Uno. If I update that one to Uno.UI 3.10. it fails on build with NameScope-Errors if I have DataTemplate in use. 

Steps to resolve:
Create a new Uno-project and replace the "Hello-World"-Textbox in the Mainpage with this one:
```
<TextBox Text="Test-Textbox"
                         Header="Name" Height="68"
                         Margin="20" BorderThickness="0" CornerRadius="6">
            <TextBox.HeaderTemplate>
                <DataTemplate>
                    <TextBlock Text="{Binding}" FontSize="20"/>
                </DataTemplate>
            </TextBox.HeaderTemplate>
        </TextBox>
```

This would work (run the application). But if you now add XamlFlair.Uno 1.2.10 it failes with an build-error like this:
"UnoTestNameScope\UnoTestNameScope.Droid\obj\Debug\100\g\XamlCodeGenerator\MainPage_a1d9d1bb2ca9de3384922e19add4f444.g.cs(143,16,143,21): error CS1061: "NameScope" enthält keine Definition für "Owner", und es konnte keine zugängliche Owner-Erweiterungsmethode gefunden werden, die ein erstes Argument vom Typ "NameScope" akzeptiert (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis)."

(Missing "Owner" on "NameScope"). I assume this is due to the fact that XamlFlair.Uno uses an older reference of Uno (3.5) and they collide in any way - though I do not know the exact reason.

**Comment by XamlFlair** [comment]
@TopperDEL  Thanks for reporting this, I noticed yesterday that 3.10 was just released and I plan to update XamlFlair sometime this week to use 3.10, I'll reply to this thread once it's ready 👍

**Comment by assassin316** [comment]
@TopperDEL  latest XamlFlair.Uno release just went out with Uno 3.10.7 support. Try it out and let me know if it works.

**Comment by XamlFlair** [comment]
@TopperDEL  if the latest version fixes your issue, please go ahead and close the issue. Thanks.

**Comment by TopperDEL** [comment]
Sorry, haven't had the time to check this until now. But I can confirm that version 1.2.11 works again. Thank you!

**Comment by XamlFlair** [comment]
@TopperDEL glad to hear👍
